### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by Rover656** [widd/kitsune#11]
Hi there,
I am trying to run KitSune on my server but i have 1 major issue. When I log in, it instantly disconnects me again. Could you please help me? Here is the log:
`09:11:53 [Debug] > Received <msg t='sys'><body action='verChk' r='0'><ver v='153' /></body></msg>
09:11:53 [Debug] > Outgoing: <msg t='sys'><body action='apiOK' r='0'></body></msg>
09:11:53 [Debug] > Received <msg t='sys'><body action='login' r='0'><login z='w1'><nick><![CDATA[test]]></nick><pword><![CDATA[12daf9ae8e5303254c6e5a332f155e641aa731491d36ba7179cc6f36928521eb]]></pword></login></body></msg>
09:11:53 [Notice] > test is attempting to login
09:11:53 [Debug] > Removing penguino
09:11:53 [Notice] > Player disconnected`
Looking forward to a reply!

**Comment by rushilsrivastava** [comment]
What type of loader are you using? Also, please format your issue correctly so it is easier to read.

**Comment by valid22** [comment]
ref: https://github.com/widd/kitsune/issues/12

**Comment by widd** [comment]
Fixed in widd/kitsune-register@bbce10c
