### ISSUE TITLE
Multi DB Connections

### ISSUE THREAD

**Issue by valid22** [widd/kitsune#5]
Just a query, why do Kitsune prefer to use multiple database connections for a single threaded server?
Kitsune is single threaded it executes requests / packets one-by-one, only after previous completed. So why does it need to put a load of 1db/20 peng to the database?

**Comment by widd** [comment]
This is a leftover design flaw from @TunnelBlanket's codebase. I plan on replacing it in the future.

**Comment by Baysul** [comment]
I've sent in a pull request with adjustments to the **DatabaseManager** class that makes it so that every user on the server shares a single connection.
See: https://github.com/widd/kitsune/pull/7
